apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: vault
      version: ">=0.11.0"
  values:
    server:
      tag: latest
      dev:
        enabled: true
        devRootToken: "root"
    ui:
      enabled: true
  interval: 1h0m0s
  releaseName: vault
  targetNamespace: vault
  install:
    crds: Create
  upgrade:
    crds: CreateReplace